### ISSUE TITLE
New install help

### ISSUE THREAD

**Issue by mattapperson** [JWDeveloper/JWManagement#118]
Evening brothers!

I was just trying to stand up an instance of your software and am having an issue. I am a Node dev, but never used meteor in a meaningful way... so I am a little lost. I am running, but the user does not seem to be an admin, any tips on how to make my first user an admin?

**Comment by 51773ELLIS** [comment]
Evening Brother! 

Im Ellis, I'd be happy to try and help you out. You may have to manually change the user setting in the (Mongo Hub) database. If you go into the 'Users' collection and then select your user, scroll down to find the project you would like to be admin for and then change it. Ive included an image to show what is should look similar too. 

(Here is the list of Users in the user collection, you will have to click the run button if you haven't already to retrieve the list of users)
![screen shot 2017-03-28 at 00 10 20](https://cloud.githubusercontent.com/assets/20007944/24381923/fca73ef4-134a-11e7-82d4-a533db403438.png)

(Here is a picture of the users file)
![screen shot 2017-03-28 at 00 07 05](https://cloud.githubusercontent.com/assets/20007944/24381901/d4c9d194-134a-11e7-9b05-ba848a1d0826.png)

Hope this helps if not feel free to message or email me at ellis@jwmanagement.org :)

**Comment by mattapperson** [comment]
@51773ELLIS I actually found the answer... I needed to setup the first user with:

``` 
{
  "roles": {
      "__global_roles__": [
            "admin",
            "support"
        ]
    }
}
```

Once I did this it all worked correctly

**Comment by mattapperson** [comment]
I might recommend an update to the docs to make this more clear? I can prob PR it later this week if you like?

**Comment by MarvinZeising** [comment]
Hey Matt,
I'd like to join the conversation if I may.

I'm amazed that you found out about the support role, since AFAIK it's not documented anywhere.
Very good!

Though this support role is meant only for us as supporters of the system.
And putting the admin role into the __global_roles__ object is a hack that should not be necessary if the admin role is given for a certain project.

We don't use either of these in development ourselves, so IMHO I don't think that other collaborators would need it.

By the way: How are you making out, getting to know the way we developed JW Management? And what do you think of it, if I may ask?

**Comment by mattapperson** [comment]
@MarvinZeising yea, been doing software dev for almost a decade now, 7 of that has been in JS/Node so I find my way around easy enough 😊 

Overall I think it's good. I am not a Meteor fan, but thats a preference thing 😊.

My only real suggestion would be to break up the website from the app... that way if a hall/ a halls elders would rather host things privately for the congregation, its a little less confusing. 
Attempting to self-host is exactly why I did/will need the support role though ;) 


All in all, great work here brothers!

**Comment by MarvinZeising** [comment]
Impressive 👍🏼

Self-hosting this app will be a challenge in my opinion, because we don't develop it for that.
Also it'd be a rather expensive and effortful solution for your congregation's cart witnessing needs (at least if you pay similar amounts to what we pay according to [/en/donate](https://www.jwmanagement.org/en/donate)).
Furthermore when we get ready with the mobile apps for iOS and Android you'd have to deploy your own app to the app stores since they're connected with our website. Otherwise the publishers would loose this feature.

Thank you very much!

**Comment by mattapperson** [comment]
as far as mobile apps go, I agree. Not my choice though lol.

As for hosting... no you guys WAY over pay 😊 I recommend you take a look at zeit now. Using the meteor-now cli tool you can deploy new builds with:
`meteor-now -d -e MONGO_URL="<MONGO URL>" -e ROOT_URL="<URL HERE>" -e NODE_ENV=production`
Cost would be $15/mo USD, a fraction of your current costs and much easier to manage

**Comment by MarvinZeising** [comment]
Good idea!

Please consider this, though:
First of all, we can't use the suggested sandbox free tier from mLab, because that one has no oplog support, which would slow everything dramatically down (yep, already tried that). We still need to pay for the $15 instance.

With the provider for server instance, you're right. It wouldn't be easier to manage (actually Galaxy's upload command is shorter) but $15/mo would be cheaper.
Although of course, a solution where some guys wrote a quick upload script for a general hosting provider, can't reach the possibilities, simplicity and stability of a service dedicated to this type of applications.
For instance what if the app crashed due to an error? That happens. More often than I'd like. Galaxy automatically redeploys a new container in a fraction of time. With Zeit we would have to think about how we could setup such a solution.
What's with log management? Can I access the logs online (like in Galaxy) or would I always have to login via SSH on a Zeit server? Would that even be possible? We really need to be able to see the logs.
What's with RAM size? How about the processor? How fast or slow is the server? I can't find anything about that.
Also a short quote from the meteor-now repo:

> __Can I use this in production?__
> Sort of! Now supports dynamic autoscaling of apps, but unfortunately at the moment they do not support sticky sessions, so some of your users may have issues of being randomly logged out and losing Session data.

Not so nice.

Second, the free OSS version of Zeit now wouldn't fit of course.
The Premium version has a bandwidth limitation of 50GB/mo. The currently deployed version of the app is about 3,5MB big. According to Google Analytics, every day the app gets accessed about 2500 times. Let it be 3000 if the system continues to grow and we're at around 300GB/mo which is 6 times the Premium version and therefore would result in about $80/mo. That is $30 more than we pay for the best solution for meteor apps on the market, where I don't have to care about anything.

**Comment by mattapperson** [comment]
True, mLab is a must (for us we already pay for another project so it just rides along for free so I forgot that 😊 ). As for for the rest... I intent was to just share what I was using, but to also state that for us (and perhaps others who wish to self host) the cost is not always anywhere near as high as someone deploying as a platform for many.

But as for zeit, on crash, the instance will auto reload, so little to worry about there. Also Zeit is a multi-host system so if lets say Amazon EC2 is down, it will use Google Compute Engine... thus making it very resilient. There is no SSH access, as the deployments are immutable... so I recommend the free tier of https://sentry.io/ or https://www.loggly.com. (for dev https://logs.now.sh works really well too). The reason you can't find anything on specs is because there is none to see... zeit scales your app to whatever it needs to be to meet your demand, all at no cost (assuming you are within bandwidth)

As for pricing... its a lie 😊 Zeit says there is a limit, but in reality it does not yet so its unlimited for that cost... you are right though to not count on that, but I would seriously question if you are really using 300gb a mo. The app's JS, CSS, and images will be cached by a users browser, so it is not like every day 3.5mb is being downloaded by each of those users.

That said, its what works best for you.
