### ISSUE TITLE
Cant approve Request

### ISSUE THREAD

**Issue by 3djevon** [JWDeveloper/JWManagement#210]
I cant approve request for a shift. I click on approve and nothing happens.

**Comment by 51773ELLIS** [comment]
Currently, shifts have been set up so that each shift has to have a team captain/leader. It may be that the neither of the publishers within the shift you are trying to approve have been predefined as being able to have that role. 

Please check the publishers role in the users page: (See the images below as a reference)

<img width="1141" alt="screen shot 2018-08-31 at 21 43 34" src="https://user-images.githubusercontent.com/20007944/44935227-c0a3d800-ad67-11e8-880e-4de655e76c85.png">
<img width="602" alt="screen shot 2018-08-31 at 21 43 54" src="https://user-images.githubusercontent.com/20007944/44935228-c0a3d800-ad67-11e8-816a-029767c66762.png">
