### ISSUE TITLE
Contact Cards

### ISSUE THREAD

**Issue by datascientistgonzo** [JWDeveloper/JWManagement#407]
Since we can now also report the distribution of contact cards, it would be nice if the publishers could also enter this in the JW Management Report.

**Comment by mh166** [comment]
Contact cards have been part of JW Management since the beginning of this project, from what I've seen in [the source](https://github.com/JWDeveloper/JWManagement/blob/6ec3f19bd35af9dd7185de5857c1c20022276598/client/views/pages/store/store.coffee#L115). You just have to add it to your Store Room. :) 

![image](https://user-images.githubusercontent.com/3167596/62571996-07ad1e00-b893-11e9-94ad-ee8b0467f561.png)

**Comment by datascientistgonzo** [comment]
Wow, that's great! I wasn't expecting that. Many thanks for the quick answer! You were ahead of time!
